version: "3"
services:
  app:
    env_file:
      - .env
    container_name: vermelha_adminPage
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_boilerplate
      POSTGRES_USER: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
        - PGADMIN_CONFIG_SERVER_MODE=False
        - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
        - "${PGADMIN_PORT:-8080}:80"
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   user: root
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - .env
  #   links:
  #     - postgres

volumes:
  postgres:
    driver: local
